# Use an official PHP runtime as a parent image
  FROM php:8.1-apache

  # Install required PHP extensions
  RUN docker-php-ext-install pdo_mysql

  # Set working directory
  WORKDIR /var/www/html

  # Copy the Laravel files to the container
  COPY . .

  # Set the correct permissions for storage and bootstrap/cache directories
  RUN chown -R www-data:www-data storage bootstrap/cache
  RUN chmod -R 775 storage bootstrap/cache

#    acme.demo.example:
#        class:     Acme\DemoBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
#        calls:
#            - [setService, ["@service_id"]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
